# Generated by Django 5.1.5 on 2025-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookentry",
            name="sender_local_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestbookentry",
            name="synchronized_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestbookentry",
            name="time_offset",
            field=models.FloatField(
                blank=True,
                help_text="Offset in seconds from coordinator time",
                null=True,
            ),
        ),
    ]
